version: 2
updates:
  - package-ecosystem: nuget
    directory: "/Source/ChargifyDirectExample.MVC" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
